[colors.bright]
black = "0x555753"
blue = "0x729fcf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7fa8"
red = "0xef2929"
white = "0xeeeecc"
yellow = "0xfce94f"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x44475a"

[colors.normal]
black = "0x2e3436"
blue = "0x3465a4"
cyan = "0x06989a"
green = "0x4e9a06"
magenta = "0x75507b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xc4a000"

[colors.primary]
background = "0x2e3436"
foreground = "0xc8c8c8"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = '\'
key = 10
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 18
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "¬"
key = "Key6"
mods = "Alt"

[[keyboard.bindings]]
chars = "{"
key = 39
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 42
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 33
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 30
mods = "Alt"

[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00068"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00069"
key = "Key9"
mods = "Control"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
decorations = "transparent"
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
