# Hydrogen
prefer_small_ascii = true
spacing         = 2
padding         = 2
separator       = ""
key_color       = "Yellow"
separator_color = "White"

[palette]
type = "Full"
visible = false


[box]
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[keys]
host            = " "
kernel          = ""
battery         = ""
os              = ""
terminal        = ""
shell           = ""
packages        = ""
uptime          = "羽"
memory          = ""
machine         = ""
local_ip        = ""
backlight       = "盛"
resolution      = " x "
cpu_load        = " %"
cpu             = ""
