##    Key bindings    ##

# Splits
bind v split-window -h -c '#{pane_current_path}'
bind h split-window -v -c '#{pane_current_path}'
bind-key -n 'C-f' resize-pane -Z

# Windows
bind-key -n 'C-w' new-window -c '#{pane_current_path}'
bind-key -n 'C-q' confirm-before -p "kill-window #W? (y/n)" kill-window


# Tmux <-> Vim pane navigation
not_tmux='#{m/r:(n?vim|fzf),#{pane_title}}'

bind-key -n 'C-h' display-message "title=#{pane_title} match=#{m/r:(n?vim|fzf),#{pane_title}}"

bind-key -n 'C-Left' if-shell -F "$not_tmux" 'send-keys' 'select-pane -L'
bind-key -n 'C-Down' if-shell -F "$not_tmux" 'send-keys' 'select-pane -D'
bind-key -n 'C-Up' if-shell -F "$not_tmux" 'send-keys' 'select-pane -U'
bind-key -n 'C-Right' if-shell -F "$not_tmux" 'send-keys' 'select-pane -R'


# vi:syntax=tmux
